routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home')->middleware('verified');

Auth::routes(['verify' => true]);

Route::get('/stream', 'HomeController@stream')->name('stream')->middleware('verified');

Route::group( ['middleware' => ['auth']], function() {
    Route::resource('courses', 'CourseController');
    Route::resource('roles', 'RoleController');
    Route::resource('lessons', 'LessonController')->except('create');
    Route::get('/lessons/create/{course}', 'LessonController@create')->name('lessons.create');
});

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Entities\Course;
use App\Http\Requests\Lesson\CreateRequest;
use App\Repositories\Contracts\LessonRepositoryInterface;
use App\Traits\Authorizable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use LMS\Modules\Lessons\Usescases\Contracts\{CreateLessonUsecaseInterface,
    DeleteLessonUsescaseInterface,
    ShowLessonUsecaseInterface,
    UpdateLessonUsescaseInterface};

class LessonController extends Controller
{
    use Authorizable;
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param int $course
     * @return \Illuminate\Http\Response
     */
    public function create(Course $course)
    {
        return view('lessons.create', compact('course'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $request
     * @param CreateLessonUsecaseInterface $createLessonUsecase
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request, CreateLessonUsecaseInterface $createLessonUsecase)
    {
        try {
            $result = $createLessonUsecase->handle($request->all(), auth()->user()->id);
            if($result['data']){
                flash('Clase creada correctamente');
            } else {
                flash(implode('-', $result['errors']), 'error');
                throw new \Exception('error create course');
            }
            return redirect()->route('courses.edit', $request->get('course_id'));
        } catch (\Exception $e){

            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @param ShowLessonUsecaseInterface $lessonUsecase
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function show($id, ShowLessonUsecaseInterface $lessonUsecase)
    {
        $response = $lessonUsecase->handle($id, Auth::user()->id);
        $lesson = $response['data']['lesson'];
        $subscribed = $response['data']['subscribed'];
        if(!$subscribed){
            return redirect()->route("courses.show", $lesson->course->id);
        }

        return view('lessons.show', compact('lesson', 'subscribed'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @param LessonRepositoryInterface $lessonRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id, LessonRepositoryInterface $lessonRepository)
    {
        $lesson = $lessonRepository->findById($id);

        return view('lessons.edit', compact('lesson'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @param UpdateLessonUsescaseInterface $updateLessonUsescase
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id, UpdateLessonUsescaseInterface $updateLessonUsescase)
    {
        try {
            $updateLessonUsescase->handle($id, $request->all());
            flash('Lección guardada correctamente');
        } catch (\Exception $e){
            flash('No se ha podido guardar la lección', 'error');
        }
        return  redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @param DeleteLessonUsescaseInterface $deleteLessonUsescase
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, DeleteLessonUsescaseInterface $deleteLessonUsescase)
    {
        try {
            $deleteLessonUsescase->handle($id);
            flash('Lección eliminada correctamente');
        } catch (\Exception $e){
            flash('No se ha podido eliminar la lección', 'error');
        }
        return redirect()->back();
    }
}

resources/views/lessons/create.blade.php
@extends('layouts.master')

@section('styles')
    <link rel="stylesheet" href="{{asset('vendor/laraberg/css/laraberg.css')}}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                {{ Form::open(['url' => route('lessons.store')]) }}
                {{ Form::hidden('course_id', $course->id) }}
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">@lang('lesson/fields.courses')</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">@lang('lesson/fields.title')</label>
                            <input type="text" id="title" value="{{old('title')}}" name="title" class="form-control">
                            @if ($errors->has('title'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                        </div>
                        <textarea id="laraberg" {{old('content')}} name="content" hidden></textarea>
                        @if ($errors->has('content'))
                            <span class="help-block">
                                <strong class="text-danger">{{ $errors->first('content') }}</strong>
                            </span>
                        @endif
                    </div>
                    <!-- /.card-body -->
                    <div class="col-12">
                        <a href="{{ route('courses.index') }}" class="btn btn-secondary">@lang('general.cancel')</a>
                        <input type="submit" value="@lang('lesson/actions.create')" class="btn btn-success float-right">
                    </div>
                </div>
            </div>
            <!-- /.card -->

            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://unpkg.com/react@16.8.6/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/moment@2.24.0/min/moment.min.js"></script>
    <script src="{{ asset('vendor/laraberg/js/laraberg.js') }}"></script>
    <script>
        Laraberg.init('laraberg')
    </script>
@endsection

resources/views/lessons/edit.blade.php
@extends('layouts.master')

@section('styles')
    <link rel="stylesheet" href="{{asset('vendor/laraberg/css/laraberg.css')}}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                {{ Form::open(['url' => route('lessons.update', $lesson->id)]) }}
                {{ Form::hidden('course_id', $lesson->course_id) }}
                @method('PUT')
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">@lang('lesson/fields.courses')</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">@lang('lesson/fields.title')</label>
                            <input type="text" id="title" value="{{old('title', $lesson->title)}}" name="title" class="form-control">
                            @if ($errors->has('title'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                        </div>
                        <textarea id="laraberg" name="content" hidden>{{old('content', $lesson->content)}}</textarea>
                        @if ($errors->has('content'))
                            <span class="help-block">
                                <strong class="text-danger">{{ $errors->first('content') }}</strong>
                            </span>
                        @endif
                    </div>
                    <!-- /.card-body -->
                    <div class="col-12">
                        <a href="{{ route('courses.index') }}" class="btn btn-secondary">@lang('general.cancel')</a>
                        <input type="submit" value="@lang('general.save')" class="btn btn-success float-right">
                    </div>
                </div>
            </div>
            <!-- /.card -->

            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://unpkg.com/react@16.8.6/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/moment@2.24.0/min/moment.min.js"></script>
    <script src="{{ asset('vendor/laraberg/js/laraberg.js') }}"></script>
    <script>
        Laraberg.init('laraberg')
    </script>
@endsection

resources/views/lessons/show.blade.php
@extends('layouts.master')
@section('styles')
    <link rel="stylesheet" href="{{asset('vendor/laraberg/css/laraberg.css')}}">
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><b>@lang('lesson/lessons.lesson'):</b> {{ $lesson->title }}</div>
                    <div class="card-body">
                        {!! $lesson->content !!}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <chat :user="{{ auth()->user() }}" :resource="{{ $lesson->id }}" :type="'lesson'"></chat>
            </div>
        </div>
    </div>
@endsection