routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home')->middleware('verified');

Auth::routes(['verify' => true]);

Route::get('/stream', 'HomeController@stream')->name('stream')->middleware('verified');

Route::group( ['middleware' => ['auth']], function() {
    Route::resource('courses', 'CourseController');
    Route::resource('roles', 'RoleController');
    Route::resource('lessons', 'LessonController')->except('create');
    Route::get('/lessons/create/{course}', 'LessonController@create')->name('lessons.create');
});

resources/views/courses/create.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-12">
    {{ Form::open(['url' => route('courses.store')]) }}
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">@lang('course/fields.courses')</h3>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label for="name">@lang('course/fields.name')</label>
                <input type="text" id="name"  name="name" class="form-control">
                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong class="text-danger">{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group">
                <label for="description">@lang('course/fields.description')</label>
                <textarea id="description" name="description" class="form-control" rows="4" maxlength="150"></textarea>
                @if ($errors->has('description'))
                    <span class="help-block">
                        <strong class="text-danger">{{ $errors->first('description') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group">
                <label for="teacher_id">@lang('course/fields.teacher')</label>
                {{ Form::select('teacher_id', $users, null, ['class' => 'form-control custom-select']) }}
                @if ($errors->has('teacher_id'))
                    <span class="help-block">
                        <strong class="text-danger">{{ $errors->first('teacher_id') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <div class="col-12">
        <a href="{{ route('courses.index') }}" class="btn btn-secondary">@lang('general.cancel')</a>
        <input type="submit" value="@lang('course/actions.create')" class="btn btn-success float-right">
    </div>
    {{ Form::close() }}
</div>
</div>

</section>
<!-- /.content -->
@endsection

@section('scripts')
<script src="{{ asset('js/jquery-3.1.1.slim.min.js') }}"></script>
<script src="{{ asset('js/remaining_characters.js') }}"></script>
<script type="text/javascript">
    $("#description").remainingCharacters({
      label: {
        tag: 'p',
        id: null,
        class: 'badge badge-primary',
        invalidClass: 'is-invalid'
      },
      text: '{n} characters remaining'
    });

</script>
@endsection



resources/views/courses/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-12">
    {{ Form::open(['url' => route('courses.update', $course->id), 'method' => 'PUT']) }}
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">@lang('course/fields.courses')</h3>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label for="name">@lang('course/fields.name')</label>
                <input type="text" id="name"  name="name" value="{{ old('name', $course->name) }}" class="form-control">
                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong class="text-danger">{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group">
                <label for="description">@lang('course/fields.description')</label>
                <textarea id="description" name="description" class="form-control" rows="4" maxlength="150">{{ old('description', $course->description) }}</textarea>
                @if ($errors->has('description'))
                    <span class="help-block">
                        <strong class="text-danger">{{ $errors->first('description') }}</strong>
                    </span>
                @endif
            </div>
            <div class="form-group">
                <label for="teacher_id">@lang('course/fields.teacher')</label>
                {{ Form::select('teacher_id', $users, old('teacher_id', $course->teacher_id), ['class' => 'form-control custom-select']) }}
                @if ($errors->has('teacher_id'))
                    <span class="help-block">
                        <strong class="text-danger">{{ $errors->first('teacher_id') }}</strong>
                    </span>
                @endif
            </div>
            <div class="col-12">
                <a href="{{ route('courses.index') }}" class="btn btn-secondary">@lang('general.cancel')</a>
                <input type="submit" value="@lang('course/actions.update')" class="btn btn-primary float-right">
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    {{ Form::close() }}
</div>

<div class="col-md-12">
    <div id="accordion">
        <!-- we are adding the .class so bootstrap.js collapse plugin detects it -->
        <div class="card card-primary">
            <div class="card-header d-flex p-0">
                <h4 class="card-title p-3">
                    <a data-toggle="collapse" aria-expanded="true" data-parent="#accordion" href="#lessons">
                        Lessons
                    </a>
                </h4>
                <ul class="nav nav-pills ml-auto p-2">
                    <li class="nav-item">
                        @can('edit_lessons')
                            <a href="{{ route('lessons.create', $course->id) }}" class="btn btn-primary">@lang('general.new')</a>
                        @endcan
                    </li>
                </ul>
            </div>
            <div id="lessons" class="panel-collapse collapse show">
                <div class="card-body">
                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">@lang('lesson/fields.id')</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">@lang('lesson/fields.title')</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label=""></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($lessons as $lesson)
                                    <tr role="row" class="odd">
                                        <td class="sorting_1">{{ $lesson->id }}</td>
                                        <td>{{ $lesson->title }}</td>
                                        <td>
                                            <a href="{{ route('lessons.edit', $lesson->id) }}" class="btn btn-primary float-left">@lang('course/actions.edit')</a>
                                            @if($lesson->status == \App\Enums\LessonStatus::DISABLED)
                                                {{ Form::open(['url' => route('lessons.update', $lesson->id), 'method' => 'PUT']) }}
                                                    <input type="hidden" name="status" value="{{ \App\Enums\LessonStatus::ENABLED }}">
                                                    <button type="submit" value="" class="btn btn-success float-right">@lang('lesson/actions.restore')</button>
                                                {{ Form::close() }}
                                            @endif
                                            {{ Form::open(['url' => route('lessons.destroy', $lesson->id), 'method' => 'DELETE']) }}
                                                <button type="submit" value="" class="btn btn-danger float-right">@lang('lesson/actions.delete')</button>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">@lang('lesson/fields.id')</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">@lang('lesson/fields.title')</th>
                                    <th rowspan="1" colspan="1"></th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- /.content -->
@endsection

@section('scripts')
<script src="{{ asset('js/jquery-3.1.1.slim.min.js') }}"></script>
<script src="{{ asset('js/remaining_characters.js') }}"></script>
<script type="text/javascript">
    $("#description").remainingCharacters({
      label: {
        tag: 'p',
        id: null,
        class: 'badge badge-primary',
        invalidClass: 'is-invalid'
      },
      text: '{n} characters remaining'
    });

</script>
@endsection

resources/views/courses/index.blade.php
@extends('layouts.master')

@section('content')
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h3 class="card-title mx-auto w-100">@lang('course/actions.index')</h3>
                <a href="{{ route('courses.create') }}" class="btn btn-success">@lang('course/actions.new')</a>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">@lang('course/fields.id')</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">@lang('course/fields.name')</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">@lang('course/fields.description')</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="">@lang('course/fields.teacher')</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label=""></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($courses as $course)
                            <tr role="row" class="odd">
                                <td class="sorting_1">{{ $course->id }}</td>
                                <td>{{ $course->name }}</td>
                                <td>{{ $course->description }}</td>
                                <td>{{ $course->teacher->name }}</td>
                                <td>
                                    <a href="{{ route('courses.edit', $course->id) }}" class="btn btn-primary float-left"><i class="fa fa-edit"></i></a>
                                    @if($course->status == \App\Enums\CourseStatus::DISABLED)
                                        {{ Form::open(['url' => route('courses.update', $course->id), 'method' => 'PUT', 'class' => 'form-inline']) }}
                                            <input type="hidden" name="status" value="{{ \App\Enums\CourseStatus::ENABLED }}">
                                            <button type="submit" value="" class="btn btn-success float-right"><i class="fa fa-eye"></i></button>
                                        {{ Form::close() }}
                                    @endif
                                    {{ Form::open(['url' => route('courses.destroy', $course->id), 'method' => 'DELETE', 'class' => 'form-inline']) }}
                                    <button type="submit" value="@lang('course/actions.delete')" class="btn btn-danger float-right"> <i class="fa fa-trash"></i> </button>
                                    {{ Form::close() }}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th rowspan="1" colspan="1">@lang('course/fields.id')</th>
                                <th rowspan="1" colspan="1">@lang('course/fields.name')</th>
                                <th rowspan="1" colspan="1">@lang('course/fields.description')</th>
                                <th rowspan="1" colspan="1">@lang('course/fields.teacher')</th>
                                <th rowspan="1" colspan="1"></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.card-body -->
</div>
<!-- /.card -->

</div>

@endsection

resources/views/courses/show.blade.php
@extends('layouts.master')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-5">
                                <h5>{{$course->name}}</h5>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        @forelse ($lessons as $lesson)
                            <div id="accordion">
                                <div class="card card-primary">
                                    <div class="card-header d-flex p-0">
                                        <h4 class="card-title p-3">
                                            <a  href="{{route('lessons.show', $lesson->id)}}">
                                                {{ $lesson->title }}
                                            </a>
                                        </h4>
                                        <ul class="nav nav-pills ml-auto p-2">
                                            <li class="nav-item">
                                                <a class="btn btn-primary" href="{{route('lessons.show', $lesson->id)}}">@lang('general.show')</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @empty
                            <p>@lang('lesson/lessons.not_have')</p>
                        @endforelse
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <chat :user="{{ auth()->user() }}" :resource="{{ $course->id }}" :type='"course"'></chat>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        const subscribed = Boolean({!! $subscribed !!})
        if(!subscribed){
            Swal.fire({
                title: 'Do you want subscribe this course',
                inputAttributes: {
                    autocapitalize: 'true'
                },
                showCancelButton: true,
                confirmButtonText: 'Subscribe',
                showLoaderOnConfirm: true,
                preConfirm: (login) => {
                    return $.ajax({
                        type: "POST",
                        url: `/api/subscribe/{!! $course->id !!}`,
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        cache: false,
                        success: function(response) {
                            swal(
                                "Sccess!",
                                "Your note has been saved!",
                                "success"
                            )
                        },
                        failure: function (response) {
                            swal(
                                "Internal Error",
                                "Oops, your note was not saved.", // had a missing comma
                                "error"
                            )
                        }
                    });
                },
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result.value) {
                    Swal.fire({
                        title: `Suscrito`,
                    })
                }
                if(result.dismiss) {
                    window.location.replace("{!! route('home') !!}");
                }
                console.log(result);
            })
        }

    </script>
@endsection